N-able (SolarWinds) N-central/HuntressAgentDeployment-macOS.sh

- add beta deployment script for macOS Agent with N-Able N-Central
- documentation available [here](https://support.huntress.io/hc/en-us/articles/7875349651987)

N-Central macOS Beta Deployment Script

---

Powershell/InstallHuntress.powershellv2.ps1

Now waits 15 seconds after attempting Uninstall.exe before manually wiping directory and registry keys. Host isolation releases properly now on uninstall.

PoSh: fix uninstall behavior

---

Bash/InstallHuntress-macOS-bash.sh
Bash/README.md

This PR is to provide a generic bash installer for macOS that can be used in RMMs where we don't have explicit documentation. This script is based on the same script used for the RMMs, with some slight modifications to make it easier for partners to use.

Generic macOS Installer Script

---

Powershell/InstallHuntress.powershellv2.ps1

- Added kernel 6.2 checks so that when we check for running and installed services we check for EDR as well. Inform the user and log if EDR will not be available. 
- Adjusted install timeout value to 120 and moved it to the "user modified variables" section. 
- Improved AccountKey and OrgKey field checks, should no longer be possible to install with the placeholder value.
- Squashed a couple bugs that lead to incomplete logs.
- Converted service check to use array, will be easier to add future services to be checked.

Service check improvements, EDR/kernel 6.2+ check

---

Powershell/InstallHuntress.powershellv2.ps1

We had a bit of a logic error - tags that were hardcoded in the top of the script weren't being used because we were always checking for the presence of tags passed in as an arg, then if they weren't we were skipping the tags. This should fix it.

Updated to correctly handle if TAGS are hardcoded in script

---

Atera/.gitattributes

Now that we provide scripts for macOS and Windows, line endings are important to consider given the variety of ways that users obtain and utilize our scripts within RMM tools.
The issue was uncovered during a support interaction, and validated from [this](https://stackoverflow.com/questions/39527571/are-shell-scripts-sensitive-to-encoding-and-line-endings) helpful post.

fix line endings

---

Powershell/InstallHuntress.powershellv2.ps1

- Added more metrics to be logged for troubleshooting: Huntress portal connectivity, basic TCP/IP data, Windows patch level, SystemInfo output, domain connectivity, Huntress registration status 
- Sped up install for faster machines (testing shows ~9 second improvement!) 
- Sped up cleanup uninstaller for faster machines (testing shows up to 7 second improvement) 
- Sped up script slightly by tracking status pre-script run and adjusting accordingly 
- Made the installer log more visible by moving from users temp folder to the normal Huntress folder 
- Improved tracking of 32/64 bit mismatches
- Improved detection of issues with architecture, kernel versions, and PowerShell versions 
- Portal connectivity checker, if more than one URL fails the check then abort rather than create a zombie …

Speed, logging, and error handling improvements

---

ConnectWise-Automate/staged/InstallHuntress.automate.ps1

Older versions of PoSh didn't support this additive operation [Net.ServicePointManager]::SecurityProtocol += .... So switching to the more compatible binary OR operator (tested as far back as PoSh 2.0) Also cleaned up the protocol assignment to use the actual ENUM instead of the number to make it easier to read

Increased compatibility with legacy OS

---

SolarwindsRMM/scripts/InstallHuntress.SolarWindsRMM.ps1

Most of our other deploys have been altered from 30 to 120 seconds as sometimes 30 seconds just isn't quite enough. Bringing this in line with the other deploy methods. Also moved this variable to global scope so partners can more easily modify this if needed.

Install timeout extended to 120 seconds

---

Addigy/InstallHuntress-macOS-Addigy.sh

The script incorrectly referenced the lines that should be commented and uncommented.
Also transitioning to date + version number so support can keep track of what partners are doing better.

Fixed instructions for pulling top-level org

---

Powershell/InstallHuntress.powershellv2.ps1

We're currently trying to copy the debug log to the Huntress folder on uninstall. Stop doing that!
Also added a force kill on the process exe's after we stop the service to make sure they exit before we try to run the uninstallers.

Don't copy the log on uninstall

---

Bash/HuntressLegacyAgentProfile.mobileconfig
Bash/HuntressSystemExtensionProfile.mobileconfig

Create MDM profile for open beta that the [sc-111053]
**Legacy:**
* Allows Full Disk Access (FDA) for the HuntressAgent (`com.huntresslabs.www`)
**System Extension:**
* Allows Full Disk Access (FDA) for the Huntress Services (`com.huntress.app` and `com.huntress.sysext`)
* Allowing for Installation of System Extension
* Allowing for Installation of Network Extension
**Testing:**
* [See shortcut for testing](https://app.shortcut.com/huntress/story/111053/create-mdm-profile-for-open-beta-that-the-customer-can-import-into-their-mdms#activity-111423)
**KB folks**
* If useful [Here are some screen shots](https://app.shortcut.com/huntress/story/111053/create-mdm-profile-for-open-beta-that-the-customer-can-import-into-their-mdms#activity-111428)

Adding comprehensive profiles for legacy and system extension agents

---

Bash/HuntressSystemExtensionProfile.mobileconfig

Fix an issue where FDA access was given to the Huntress Daemon (`com.huntress.app`) instead of the Agent (`com.huntress.HuntressAgent`).

Replace com.huntress.app with com.huntress.HuntressAgent

---

Powershell/InstallHuntress.powershellv2.ps1

This PR introduces a delayed retry when downloading the Huntress Installer fails, and prevents a path conflict by deleting the previous Huntress Installer if it already exists.

Retry error downloading Huntress Installer

---

Powershell/InstallHuntress.powershellv2.ps1

This PR fixes an issue where a conflicting file could prevent the creation of the Huntress installation directory by renaming the conflicting file when present.

Handle file conflict with installation directory

---

Powershell/InstallHuntress.powershellv2.ps1

This script version should be kept up to date as Support uses it to confirm which version of our script partners are using. It's vital for troubleshooting.

Updating Script version

---

Addigy/InstallHuntress-macOS-Addigy.sh

A quick change to Addigy deployment script to log the `POLICY_PATH`.
We see a couple tickets about this and it's not clear where the problem is. 
Having the `POLICY_PATH` printed to the logs would help discern what's going wrong quicker.

Add policy path to the log. helpful when the deployment fails

---

Addigy/InstallHuntress-macOS-Addigy.sh
Bash/InstallHuntress-macOS-bash.sh

Effectively passing a multi word organization to the install script would break and only register the first word.
This is due to shell quoting compounded by a script calling another script.
* Use the old way of calling scripts. 
(Note: there's probably a better way to do this, but I'm choosing not to fight *sh space/quoting/IFS issues)
* Amend Addigy logging statements, since multiple scripts end up writing to the same log.
* Effectively comment out `curl` commands and modify the `HuntressMacInstall.sh` to exit after creating the hagent.yml
* run `POLICY_PATH="Fireline Partners | Anchor Point IT Solutions" zsh -x ./InstallHuntress-macOS-Addigy.sh`
* validate that the org name includes "Fireline Partners"
There are other files that also need to be update (Ninja, Kaseya, etc).
I intend to …

Fix deployment script to accept multiple [sc-136060]

---

Atera/InstallHuntress-macOS-Atera.sh
Datto-RMM/Mac/command.bat
N-able (SolarWinds) N-central/InstallHuntress-macOS-nable.sh
Ninja-RMM/InstallHuntress-macOS-NinjaRMM.sh
Syncro/InstallHuntress-macOS-Syncro.sh

Part of Fix deployment script to accept multiple [sc-136060] story
Follow up PR from https://github.com/huntresslabs/deployment-scripts/pull/88
Fix the other mac scripts.
~NB: This is in draft, pending a customer to try out the fix and incorporate that feedback.~
(slack https://huntress.slack.com/archives/C034BDN4R4J/p1720209475895639)
Customer tested #88 and works in their environment. Applying the same changes for the rest of the deployment scripts.
(Zendesk: https://huntress.zendesk.com/agent/tickets/92009)
This does not include Datto "cpt" based deployment, which was unaffected.

update other macos scripts

---

Bash/MicrosoftDefenderForEndpoint/mdatp.mobileconfig

Updates MDM Profile for MS Defender deployments.
* Allow MS autoupdate2 service to run in the background. This has two benefits; 
1) It reduces troubleshooting/support efforts when Defender show ambiguous "out of date" warnings
2) Removes the ability for the end-user to disable it, since its managed by MDM.
* Allows removal of MS defender system extensions without prompting the user
* Seamless install should imply seamless uninstall. Lack of symmetry is disorienting to the user
See internal ticket for testing details

Update Defender MDM policies to allow managed updated and silent removal

---

Bash/InstallHuntress-macOS-bash.sh

This PR updates the bash install script to handle `--tags` and `--install_system_extension` options and pass those to the "internal" install script it downloads from the Huntress CDN.

allow install script to handle tags and system extension

---

Bash/InstallHuntress-macOS-bash.sh

Story details: https://app.shortcut.com/huntress/story/135315
use `/usr/bin/env zsh` instead of `/bin/zsh`.
microsoft no likey the latter: https://learn.microsoft.com/en-us/mem/intune/apps/macos-shell-scripts

feat: [sc-135315] Update macOS deployment script for Intune

---

Bash/HuntressSystemExtensionProfile.mobileconfig
Bash/README.md

The mobileconfigs are indistinguishable from a previous version if updated, having a version number is fairly handy.
It'd help troubleshoot issues far more quickly.
While the filename is the same, the UI display would reflect this in
1. **System Settings** -> **Device Management**
2. CLI   
` profiles -C -o stdout-xml`
These would need to be updated when a new edition of the mobileconfig is made

Add a version number to human readable field

---

Datto-RMM/scripts/InstallHuntress.dattormm.comstore.ps1
Powershell/InstallHuntress.powershellv2.ps1

This PR resolves #101 by replacing calls to `Write-Output` with `LogMessage`, which writes to both the console and log file. In most cases, the `Write-Output` call was redundant since we were already calling `LogMessage`.

Fix Write-Output with unsupported parameters

---

Mosyle/InstallHuntress-macOS-Mosyle.sh
Mosyle/README.md

Per customer request, we now have a deployment script for Mosyle MDM.
This will allow the install of the agent via that MDM
Credit to @stuartjash

Add Mosyle deployment script

---

Powershell/InstallHuntress.powershellv2.ps1

- Remove/delete services when using uninstall flag (now including Huntmon) 
- Additional logging to note which user context the script is running under. For troubleshooting TP issues. 
- Warn if TP could interfere, i.e. if TP is detected (checks the service status instead of the context) 
- Script checks for assets in \Program Files\ instead of checking for services since some uninstall methods leave the services in place. This check is needed to prevent RMM's from hammering the Huntress portal with repeated installs. 
- Fixed orphan checker, should no longer go down that execution path unless an orphaned agent is actually detected. 
- Switched to using SC.exe instead of WMI calls for removing service(s), more reliable with a wider variety of machines. Using full path to avoid path …

Prep for Tamper Protection 

---

Powershell/InstallHuntress.powershellv2.ps1

- Remove/delete services when using uninstall flag
- Additional logging to note which user context the script is running under. For troubleshooting TP issues.
- Warn if TP could interfere, i.e. if TP is detected (checks the service status instead of the context)
- Script checks for assets in \Program Files\ instead of checking for services since some uninstall methods leave the services in place. This check is needed to prevent RMM's from hammering the Huntress portal with repeated installs.
- Fixed orphan checker, should no longer go down that execution path unless an orphaned agent is actually detected.
- Switched to using SC.exe instead of WMI calls for removing service(s), more reliable with a wider variety of machines

Prep for Tamper Protection

---

Powershell/InstallHuntress.powershellv2.ps1

- If IE first run has not occurred, attempt to bypass the first run setup screen via registry edit. If unable to change that reg key, cancel the function exit on network test fail and continue execution as normal. 
- Use BasicParsing for Invoke-WebRequest (brings PoSh 5.0 and under to parity with PoSh 6.0+)
- Log any IE first run issues we detect

Fix for IE first run errors

---

Powershell/InstallHuntress.powershellv2.ps1

When Huntress is uninstalled or damaged the services are often left in the "disabled" startup state. Partners attempt to repair this by reinstalling Huntress, but if the services are set to "disabled" start then they can't be manually started. We can address that by setting all non-auto start services to start automatically. SC.exe was used for compatibility, the better PoSh commands aren't available until 6.0 (most people are on 5.0).

Improved self-repair

---

Powershell/InstallHuntress.powershellv2.ps1

-Post install service repair for previous Huntress installs with services stuck in the stopped state, now checks that the service exists before proceeding with repair. 
-Logging added: show what flags the script was run with
-Removed some unused parts of a repair function we no longer need, done so partners who use the flag don't see a false message about repair being complete. Currently it acts as a -reregister flag only, but saving for potential future use.

check for service existence before taking action

---

Datto-RMM/scripts/InstallHuntress.dattormm.comstore.ps1

This ScriptType should always be set to a unique value for each 3rd party system as Support needs a way to know which script was run in order to troubleshoot.

Changed ScriptType to reflect Datto
